### ISSUE TITLE
OpenTK.Graphics.GraphicsContextException when running the demo

### ISSUE THREAD

**Issue by ArtyIF** [bepu/bepuphysics2#240]
When running the demo with the command `LD_LIBRARY_PATH=./lib dotnet run --project Demos.GL/Demos.csproj -c Release` (where `lib` contains a properly named freetype library, it's called `libfreetype.so.6` in Fedora which causes compilation issues), the demo crashes with the error:

```
Unhandled exception. OpenTK.Graphics.GraphicsContextException: Exception of type 'OpenTK.Graphics.GraphicsContextException' was thrown.
   at OpenTK.Graphics.GraphicsContext.LoadAll()
   at DemoRenderer.RenderSurface..ctor(IWindowInfo window, Int2 resolution, Boolean fullScreen, Boolean enableDeviceDebugLayer) in /home/artyif/Downloads/bepuphysics2-2.4.0/DemoRenderer.GL/RenderSurface.cs:line 32
   at Demos.GameLoop..ctor(Window window) in /home/artyif/Downloads/bepuphysics2-2.4.0/Demos/GameLoop.cs:line 26
   at Demos.Program.Main() in /home/artyif/Downloads/bepuphysics2-2.4.0/Demos/Program.cs:line 14
```

Using Fedora Linux 37 (Workstation Edition), 64-bit, GNOME 43.0 (X11). GPU is NVIDIA GeForce GTX 1050 Ti, using proprietary `nvidia` drivers

**Comment by RossNordby** [comment]
Does it still crash on latest master? (I just fixed some bitrot in Demos.GL.)

**Comment by ArtyIF** [comment]
The master version seems to target .NET 7.0, which Fedora repositories don't have yet

**Comment by ArtyIF** [comment]
After changing the target framework, the problem does seem to be solved. It loaded the car demo, with the only error popping up when closing the window (`X Error of failed request:  BadWindow (invalid Window parameter)`), which I don't think is significant or relevant to this issue
